### ISSUE TITLE
如果能加上上传路径，状态，进度条就完美了

### ISSUE THREAD

**Issue by wonderfulo** [woai3c/vue-upload-imgs#1]

**Comment by woai3c** [comment]
这个上传组件是将图片转成 base64 码，所以需要自己手动上传。状态这个可以考虑加一个，显示上传中，不过都得自己手动控制。

推荐你看一下 element ui 的上传组件，你要的功能都有。

**Comment by wonderfulo** [comment]
嗯 谢谢
