### ISSUE TITLE
添加特殊图片上传会有拉伸变形

### ISSUE THREAD

**Issue by JUNPENG1992** [woai3c/vue-upload-imgs#14]
## 添加示
![src=http___static lieyunwang com_upload2_file_201812_1546067107161558 jpg refer=http___static lieyunwang](https://user-images.githubusercontent.com/12162565/155287682-fcfaeddb-4ec9-424e-a0ed-4b1deed1c2db.jpg)
例图片
![未标题-1](https://user-images.githubusercontent.com/12162565/155287654-d48188ad-8238-49e5-b415-e7903563195f.jpg)
![test2](https://user-images.githubusercontent.com/12162565/155287666-731295eb-a148-46b9-af35-11f3f07f75ee.jpg)

## 结果
![image](https://user-images.githubusercontent.com/12162565/155287575-2d053a14-5bca-4c7f-a2e9-8526b70b558c.png)

##理想结果

图片长宽比正常

## 解决办法

```

使用background的方式，设置

 <div  :style="`
                background: url(${item.url}) no-repeat;`"
            ></div>


  background-size: contain ;
  background-position: center ;

```

**Comment by woai3c** [comment]
https://github.com/woai3c/vue-upload-imgs/commit/b9ceeda11ccba584edbcc350ec7c7ee64983d398
感谢反馈，已修复，图片忘记加 `object-fit: cover` 了。
