### ISSUE TITLE
vue3.2 在afterread函数中读取不到file，控制台显示console.log(file)为undefined

### ISSUE THREAD

**Issue by ChrisChen2580** [woai3c/vue-upload-imgs#18]
const afterRead = (index, file) => {
  console.log('after-read')
  console.log(file)
}

**Comment by ChrisChen2580** [comment]
我目前的解决办法是从files数组中读取出来

**Comment by woai3c** [comment]
感谢反馈，我复现一下。

**Comment by woai3c** [comment]
<img width="548" alt="image" src="https://user-images.githubusercontent.com/22117876/157010343-e3681a55-674d-444a-9684-800e78c23623.png">

```ts
function afterRead(file: any) {
    console.log('after-read')
    console.log(file)
}
```
我用 vue 3.2.25 版本试了一下，没有出现你说的问题。可否提供一下最小可复现问题的代码。

**Comment by ChrisChen2580** [comment]
![image](https://user-images.githubusercontent.com/73585816/157165443-b35680a3-f398-4607-8e03-8b944c11601c.png)
![image](https://user-images.githubusercontent.com/73585816/157165487-923c42d9-078e-481c-9666-d9e78c911b07.png)
![image](https://user-images.githubusercontent.com/73585816/157165543-a18c709f-4074-4317-a559-5db9ec1a2b12.png)

**Comment by ChrisChen2580** [comment]
我也不知道为什么，在其他函数里面，例如beforeremove，file是可以打印出来的

**Comment by woai3c** [comment]
我的 vue-upload-imgs 版本是 2.0.3

**Comment by woai3c** [comment]
> ![image](https://user-images.githubusercontent.com/73585816/157165443-b35680a3-f398-4607-8e03-8b944c11601c.png) ![image](https://user-images.githubusercontent.com/73585816/157165487-923c42d9-078e-481c-9666-d9e78c911b07.png) ![image](https://user-images.githubusercontent.com/73585816/157165543-a18c709f-4074-4317-a559-5db9ec1a2b12.png)

你的参数有问题，钩子函数只有一个参数，所以 file 对象是你的 `index` 参数。

**Comment by ChrisChen2580** [comment]
这样的吗，好的谢谢你

**Comment by ChrisChen2580** [comment]
这样的吗，好的谢谢你
