### ISSUE TITLE
上传组件开启 compress后，:quality="0.8", 并没有进行图片压缩

### ISSUE THREAD

**Issue by Connorig** [woai3c/vue-upload-imgs#32]
上传组件开启 compress后，:quality="0.8", 并没有进行图片压缩。
<VueUploadImgs
label="点击拍照"
:quality="0.8"
compress
:before-read="beforeRead"
:after-read="afterRead"
:before-remove="beforeRemove"
:limit="1"
:type="1"
@preview="preview"
@exceed="exceed"
@oversize="oversize"
v-model="state.files"
			/>
这是调用时的源码，请帮忙查看一下，压缩功能是否可用，谢谢

**Comment by woai3c** [comment]
> 上传组件开启 compress后，:quality="0.8", 并没有进行图片压缩。 <VueUploadImgs label="点击拍照" :quality="0.8" compress :before-read="beforeRead" :after-read="afterRead" :before-remove="beforeRemove" :limit="1" :type="1" @Preview="preview" @exceed="exceed" @oversize="oversize" v-model="state.files" /> 这是调用时的源码，请帮忙查看一下，压缩功能是否可用，谢谢

你好，刚才试了一下。不压缩和默认压缩 0.8 倍，图片大小是一样的。你只需要把 quality 的值调整到 0.8 以下，就可以看到差别，例如设为 0.7。

**Comment by Connorig** [comment]
好的，我试试，感谢&nbsp;


码农
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月17日(星期五) 晚上11:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [woai3c/vue-upload-imgs] 上传组件开启 compress后，:quality=&quot;0.8&quot;, 并没有进行图片压缩 (Issue #32)





  
上传组件开启 compress后，:quality="0.8", 并没有进行图片压缩。 <VueUploadImgs label="点击拍照" :quality="0.8" compress :before-read="beforeRead" :after-read="afterRead" :before-remove="beforeRemove" :limit="1" :type="1" @Preview="preview" @exceed="exceed" @oversize="oversize" v-model="state.files" /&gt; 这是调用时的源码，请帮忙查看一下，压缩功能是否可用，谢谢
  
你好，刚才试了一下。不压缩和默认压缩 0.8 倍，图片大小是一样的。你只需要把 quality 的值调整到 0.8 以下，就可以看到差别，例如设为 0.7。

**Comment by woai3c** [comment]
> 好的，我试试，感谢&nbsp; 码农 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年3月17日(星期五) 晚上11:21 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [woai3c/vue-upload-imgs] 上传组件开启 compress后，:quality=&quot;0.8&quot;, 并没有进行图片压缩 (Issue #32) 上传组件开启 compress后，:quality="0.8", 并没有进行图片压缩。 <VueUploadImgs label="点击拍照" :quality="0.8" compress :before-read="beforeRead" :after-read="afterRead" :before-remove="beforeRemove" :limit="1" :type="1" @Preview="preview" @exceed="exceed" @oversize="oversize" v-model="state.files" /&gt; 这是调用时的源码，请帮忙查看一下，压缩功能是否可用，谢谢 你好，刚才试了一下。不压缩和默认压缩 0.8 倍，图片大小是一样的。你只需要把 quality 的值调整到 0.8 以下，就可以看到差别，例如设为 0.7。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

不客气，有问题可以继续提 issue。
