### ISSUE TITLE
请问，页面多个vue-upload-imgs，需要怎么处理？

### ISSUE THREAD

**Issue by conku** [woai3c/vue-upload-imgs#6]
请问，页面多个vue-upload-imgs，需要怎么处理？

**Comment by woai3c** [comment]
引入多个 vue-upload-imgs 组件就行了。

**Comment by woai3c** [comment]
![image](https://user-images.githubusercontent.com/22117876/97086473-09a8fb80-1656-11eb-90f7-41fb8c9303d9.png)

可以同时使用多个组件。
